# -*- coding: utf-8 -*-
"""codigoBase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBSMg0_RWEKDvEY56Sha6X8RV4H4l37e
"""

import pandas as pd
import plotly.express as px
import streamlit as st 

#streamlit run codigoBase.py   -- > Rodar no prompt para acessar o streamlit e visualizar seu código

# LENDO O BANCO DE DADOS
casos_covid_brazil = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')

# ALTERANDO OS NOMES DAS COLUNAS
casos_covid_brazil = casos_covid_brazil.rename(columns={'newDeaths': 'Novos óbitos','newCases': 'Novos casos','deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes','totalCases_per_100k_inhabitants':'Casos por 100 mil habitantes'})

# SELECÃO DO ESTADO
estados = list(casos_covid_brazil['state'].unique())   # Cria uma lista com Todos os Estados do Banco de Dados
state = st.sidebar.selectbox('Escolha o Estado?', estados)

# SELEÇÃO DA COLUNA
colunas = ['Novos óbitos','Novos casos','Óbitos por 100 mil habitantes','Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Qual tipo de informação?', colunas)

# SELEÇÃO DAS LINHAS QUE PERTECEM AO ESTADO
casos_covid_estado = casos_covid_brazil[casos_covid_brazil['state'] == state]

fig = px.line(casos_covid_estado, x="date", y=column, title=column + ' - ' + state)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})

st.title('DADOS COVID - BRASIL')
st.write('Nessa aplicação, o usuário tem a opção de escolher o estado e o tipo de informação para mostrar o gráfico. Utilize o menu lateral para alterar a mostragem.')

st.plotly_chart(fig, use_container_width=True)

st.caption('Os dados foram obtidos a partir do site: https://github.com/wcota/covid19br')

